<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import AdminShell from '../../components/AdminShell.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import {receivables,payables,cashflow,budgets} from '../../api/mock'
const completed=[64,78,70,86,77,93,82,98,84,100,89,96]
</script>
<template><AdminShell><template #title>流程运营台</template>
  <div class="page-heading"><div><p>PROCESS OPERATIONS</p><h1>流程运营台</h1><span>流程实例、审批任务与服务时效的统一运营视图</span></div><div><button class="button secondary">导出运营报告</button><button class="button primary">＋ 发起流程</button></div></div>
  <section class="metric-grid five"><article><header><span>已发布流程</span><i>流</i></header><strong>42<small> 个</small></strong><p><b>6 个</b> 本月有版本更新</p></article><article><header><span>运行中实例</span><i>进</i></header><strong>199<small> 个</small></strong><p>其中逾期 <b>3 个</b></p></article><article><header><span>今日已办</span><i>办</i></header><strong>331<small> 项</small></strong><p>人均处理 12.6 项</p></article><article><header><span>SLA 达标率</span><i>时</i></header><strong>92.4<small> %</small></strong><p>较上月提升 2.1%</p></article><article class="warning"><header><span>超时任务</span><i>!</i></header><strong>4<small> 项</small></strong><p><b>1 项</b> 已超过 4 小时</p></article></section>
  <section class="dashboard-grid"><div class="card cash-trend"><header><div><h2>流程运行趋势</h2><p>近 12 个月发起量与办结量</p></div><div class="legend"><span><i></i>发起</span><span><i></i>办结</span></div></header><div class="chart-area"><div class="chart-scale"><span>240</span><span>180</span><span>120</span><span>60</span><span>0</span></div><div class="bar-chart"><div v-for="(v,i) in cashflow" :key="i" class="bar-group"><div><i :style="{height:v/2.3+'px'}"></i><em :style="{height:completed[i]/2.3+'px'}"></em></div><small>{{i+1}}月</small></div></div></div><footer><div><span>本月发起</span><b>1,769 个</b></div><div><span>本月办结</span><b>1,692 个</b></div><div><span>自动化处理</span><b class="positive">63.4%</b></div></footer></div>
  <div class="card action-center"><header><div><h2>今日重点待办</h2><p>按 SLA 与业务优先级排序</p></div><em>查看任务中心 →</em></header><article v-for="(x,i) in payables" :key="x.no"><time>{{['09:30','11:00','14:30','16:00'][i]}}</time><i :class="['dot',i===2?'red':i===1?'amber':'teal']"></i><div><b>{{x.supplier}}</b><small>{{x.source}} · {{x.due}}</small></div><StatusBadge :value="x.status"/></article><footer>预计今日按时办结 <b>326 项</b></footer></div></section>
  <section class="dashboard-bottom"><div class="card"><header><div><h2>活跃流程实例</h2><p>按时效风险和业务重要性排序</p></div><em>全部实例 →</em></header><table><thead><tr><th>流程 / 实例</th><th>截止</th><th>当前耗时</th><th>状态</th></tr></thead><tbody><tr v-for="x in receivables.slice(0,4)" :key="x.no"><td><b>{{x.customer}}</b><small>{{x.no}} · {{x.source}}</small></td><td :class="{'danger-text':x.status==='已逾期'}">{{x.due}}</td><td><b>{{x.amount.toFixed(1)}} 小时</b></td><td><StatusBadge :value="x.status"/></td></tr></tbody></table></div>
  <div class="card budget-brief"><header><div><h2>流程 SLA</h2><p>高频流程本月达标情况</p></div><em>时效分析 →</em></header><article v-for="x in budgets.slice(0,4)" :key="x.dept"><div><b>{{x.dept}}</b><small>{{x.subject}} · {{x.actual}} / {{x.annual}} 项</small></div><strong>{{x.rate}}%</strong><span><i :class="{warn:x.status==='预警'}" :style="{width:x.rate+'%'}"></i></span></article></div>
  <div class="card"><header><div><h2>流程版本动态</h2><p>最近发布和等待上线</p></div><em>模型库 →</em></header><div class="payment-list"><article v-for="(x,i) in payables" :key="x.no"><time><b>v{{i+2}}.{{i}}</b><small>版本</small></time><div><b>{{x.supplier}}</b><small>{{x.source}}</small></div><strong>{{x.status}}</strong></article></div></div></section>
</AdminShell></template>
