/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.bpm.deep;
import jakarta.persistence.*;import org.springframework.http.*;import org.springframework.stereotype.*;import org.springframework.transaction.annotation.*;import org.springframework.web.server.*;import java.time.*;import java.util.*;
@Service @Transactional(readOnly=true) public class DeepWorkflowService{private final EntityManager em;public DeepWorkflowService(EntityManager e){em=e;}
 @Transactional public DefinitionView create(DefinitionInput x){var d=new WorkflowDefinition(x.processKey(),x.versionNo(),x.name());em.persist(d);event("CREATE_DEFINITION",x.processKey(),x.name());return view(d);}
 @Transactional public NodeView addNode(Long id,NodeInput x){var d=definition(id);if(!"DRAFT".equals(d.status))throw conflict("已发布流程不能修改节点");if(x.sequenceNo()<1||x.slaHours()<1)throw bad("顺序和SLA必须大于零");var n=new WorkflowNode(id,x.nodeCode(),x.sequenceNo(),x.approverRole(),x.slaHours());em.persist(n);return view(n);}
 @Transactional public DefinitionView publish(Long id){var d=definition(id);if(!"DRAFT".equals(d.status))throw conflict("流程定义状态不可发布");var nodes=nodes(id);if(nodes.size()<2)throw conflict("企业流程至少配置两个审批节点");for(int i=0;i<nodes.size();i++)if(nodes.get(i).sequenceNo!=i+1)throw conflict("节点顺序必须从1连续配置");d.status="PUBLISHED";event("PUBLISH_DEFINITION",d.processKey,"v"+d.versionNo);return view(d);}
 @Transactional public InstanceView start(StartInput x){var d=definition(x.definitionId());if(!"PUBLISHED".equals(d.status))throw conflict("仅已发布流程可以发起");var ns=nodes(d.id);var i=new WorkflowInstance(x.instanceNo(),d.id,x.initiator(),x.businessKey(),ns.get(0).sequenceNo);em.persist(i);em.flush();createTask(i,ns.get(0));event("START_INSTANCE",i.instanceNo,x.businessKey());return view(i);}
 @Transactional public TaskView claim(Long id,ClaimInput x){var t=task(id);if(!"READY".equals(t.status))throw conflict("任务不可认领");t.assignee=x.assignee();t.status="CLAIMED";event("CLAIM_TASK",t.taskNo,x.assignee());return view(t);}
 @Transactional public TaskView delegate(Long id,ClaimInput x){var t=task(id);if(!"CLAIMED".equals(t.status))throw conflict("仅已认领任务可以转办");t.assignee=x.assignee();event("DELEGATE_TASK",t.taskNo,x.assignee());return view(t);}
 @Transactional public TaskView decide(Long id,DecisionInput x){var t=task(id);if(!"CLAIMED".equals(t.status))throw conflict("任务需要先认领");if(!Set.of("APPROVE","REJECT").contains(x.decision()))throw bad("决策仅支持APPROVE或REJECT");t.status="COMPLETED";t.decision=x.decision();t.comment=x.comment();var i=instance(t.instanceId);if("REJECT".equals(x.decision())){i.status="REJECTED";i.endedAt=LocalDateTime.now();}else{var ns=nodes(i.definitionId);var next=ns.stream().filter(n->n.sequenceNo>i.currentSequence).findFirst();if(next.isPresent()){i.currentSequence=next.get().sequenceNo;createTask(i,next.get());}else{i.status="COMPLETED";i.endedAt=LocalDateTime.now();}}event("DECIDE_TASK",t.taskNo,x.decision());return view(t);}
 @Transactional public int escalate(LocalDateTime asOf){var ts=em.createQuery("select t from WorkflowTask t where t.status in ('READY','CLAIMED') and t.dueAt<:d and t.escalated=false",WorkflowTask.class).setParameter("d",asOf).getResultList();ts.forEach(t->{t.escalated=true;event("ESCALATE_TASK",t.taskNo,"SLA overdue");});return ts.size();}
 public Workspace workspace(){return new Workspace(definitions(),instances(),tasks());}
 private void createTask(WorkflowInstance i,WorkflowNode n){em.persist(new WorkflowTask(i.id,n,i.instanceNo+"-T"+n.sequenceNo));}private List<WorkflowNode>nodes(Long d){return em.createQuery("select n from WorkflowNode n where n.definitionId=:d order by n.sequenceNo",WorkflowNode.class).setParameter("d",d).getResultList();}private WorkflowDefinition definition(Long id){var x=em.find(WorkflowDefinition.class,id);if(x==null)throw missing("流程定义不存在");return x;}private WorkflowTask task(Long id){var x=em.find(WorkflowTask.class,id);if(x==null)throw missing("任务不存在");return x;}private WorkflowInstance instance(Long id){var x=em.find(WorkflowInstance.class,id);if(x==null)throw missing("流程实例不存在");return x;}private void event(String a,String n,String d){em.persist(new WorkflowEvent(a,n,d));}
 private List<DefinitionView>definitions(){return em.createQuery("select d from WorkflowDefinition d order by d.id desc",WorkflowDefinition.class).getResultList().stream().map(this::view).toList();}private List<InstanceView>instances(){return em.createQuery("select i from WorkflowInstance i order by i.id desc",WorkflowInstance.class).getResultList().stream().map(this::view).toList();}private List<TaskView>tasks(){return em.createQuery("select t from WorkflowTask t order by t.id desc",WorkflowTask.class).getResultList().stream().map(this::view).toList();}
 private DefinitionView view(WorkflowDefinition d){return new DefinitionView(d.id,d.processKey,d.versionNo,d.name,d.status,d.lockVersion);}private NodeView view(WorkflowNode n){return new NodeView(n.id,n.definitionId,n.nodeCode,n.sequenceNo,n.approverRole,n.slaHours);}private InstanceView view(WorkflowInstance i){return new InstanceView(i.id,i.instanceNo,i.definitionId,i.initiator,i.businessKey,i.status,i.currentSequence,i.endedAt,i.lockVersion);}private TaskView view(WorkflowTask t){return new TaskView(t.id,t.instanceId,t.taskNo,t.assignee,t.status,t.dueAt,t.decision,t.escalated,t.lockVersion);}
 private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 public record DefinitionInput(String processKey,int versionNo,String name){}public record NodeInput(String nodeCode,int sequenceNo,String approverRole,int slaHours){}public record StartInput(String instanceNo,Long definitionId,String initiator,String businessKey){}public record ClaimInput(String assignee){}public record DecisionInput(String decision,String comment){}public record DefinitionView(Long id,String processKey,int versionNo,String name,String status,long version){}public record NodeView(Long id,Long definitionId,String nodeCode,int sequenceNo,String approverRole,int slaHours){}public record InstanceView(Long id,String instanceNo,Long definitionId,String initiator,String businessKey,String status,int currentSequence,LocalDateTime endedAt,long version){}public record TaskView(Long id,Long instanceId,String taskNo,String assignee,String status,LocalDateTime dueAt,String decision,boolean escalated,long version){}public record Workspace(List<DefinitionView>definitions,List<InstanceView>instances,List<TaskView>tasks){}
}
