-- Copyright 2026 上海如静知华信息科技有限公司
CREATE TABLE sys_user (id BIGINT PRIMARY KEY AUTO_INCREMENT,username VARCHAR(40) NOT NULL UNIQUE,password VARCHAR(100) NOT NULL,display_name VARCHAR(40) NOT NULL,role VARCHAR(20) NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE bpm_process_definition (id BIGINT PRIMARY KEY AUTO_INCREMENT,account_code VARCHAR(32) NOT NULL UNIQUE,account_name VARCHAR(80) NOT NULL,bank_name VARCHAR(80) NOT NULL,account_type VARCHAR(40) NOT NULL,balance DECIMAL(16,2) NOT NULL,available_balance DECIMAL(16,2) NOT NULL,currency VARCHAR(16) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE bpm_process_instance (id BIGINT PRIMARY KEY AUTO_INCREMENT,process_instance_no VARCHAR(32) NOT NULL UNIQUE,customer_name VARCHAR(100) NOT NULL,source_document VARCHAR(100) NOT NULL,amount DECIMAL(16,2) NOT NULL,received_amount DECIMAL(16,2) NOT NULL,due_date DATE NOT NULL,owner VARCHAR(40) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE bpm_process_task (id BIGINT PRIMARY KEY AUTO_INCREMENT,process_task_no VARCHAR(32) NOT NULL UNIQUE,supplier_name VARCHAR(100) NOT NULL,source_document VARCHAR(100) NOT NULL,amount DECIMAL(16,2) NOT NULL,paid_amount DECIMAL(16,2) NOT NULL,due_date DATE NOT NULL,applicant VARCHAR(40) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE bpm_approval_task (id BIGINT PRIMARY KEY AUTO_INCREMENT,claim_no VARCHAR(32) NOT NULL UNIQUE,claimant VARCHAR(40) NOT NULL,department VARCHAR(60) NOT NULL,category VARCHAR(40) NOT NULL,purpose VARCHAR(160) NOT NULL,amount DECIMAL(14,2) NOT NULL,expense_date DATE NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE bpm_sla_policy (id BIGINT PRIMARY KEY AUTO_INCREMENT,sla_policy_no VARCHAR(32) NOT NULL UNIQUE,department VARCHAR(60) NOT NULL,subject_name VARCHAR(60) NOT NULL,fiscal_year INT NOT NULL,annual_amount DECIMAL(16,2) NOT NULL,occupied_amount DECIMAL(16,2) NOT NULL,actual_amount DECIMAL(16,2) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE INDEX idx_bpm_process_instance_due ON bpm_process_instance(due_date,status);
CREATE INDEX idx_bpm_process_task_due ON bpm_process_task(due_date,status);
CREATE INDEX idx_bpm_expense_status ON bpm_approval_task(status,expense_date);
CREATE INDEX idx_bpm_sla_policy_year_dept ON bpm_sla_policy(fiscal_year,department);
