/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.bpm;

import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.MockMvc;import java.time.LocalDate;import java.util.regex.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc
class BpmApiIntegrationTests {
    @Autowired MockMvc mvc;
    private String login(String username,String password)throws Exception{String json=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+username+"\",\"password\":\""+password+"\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();Matcher m=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)\\\"").matcher(json);if(!m.find())throw new AssertionError("登录响应中缺少 token");return m.group(1);}
    @Test void adminCanReadProcessDashboard()throws Exception{String token=login("admin","admin123");mvc.perform(get("/api/bpm/dashboard").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.data.cashBalance").isNumber()).andExpect(jsonPath("$.data.upcomingProcessInstances").isArray());mvc.perform(get("/api/bpm/process-definitions").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(3));}
    @Test void processManagerCanCreateAndAdvanceInstance()throws Exception{String token=login("finance","finance123");String body="{\"processInstanceNo\":\"AR-TEST-001\",\"customerName\":\"测试客户\",\"sourceDocument\":\"测试合同\",\"amount\":10000,\"dueDate\":\""+LocalDate.now().plusDays(5)+"\",\"owner\":\"测试流程\"}";String json=mvc.perform(post("/api/bpm/process-instances").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("待收款")).andReturn().getResponse().getContentAsString();Matcher id=Pattern.compile("\\\"id\\\":(\\d+)").matcher(json);if(!id.find())throw new AssertionError("响应缺少 id");mvc.perform(patch("/api/bpm/process-instances/"+id.group(1)+"/progress").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"amount\":10000}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("已结清"));}
    @Test void employeeCanSubmitExpense()throws Exception{String token=login("employee","employee123");String body="{\"claimant\":\"业务员工\",\"department\":\"产品中心\",\"category\":\"交通费\",\"purpose\":\"客户访谈交通\",\"amount\":128,\"expenseDate\":\""+LocalDate.now()+"\"}";mvc.perform(post("/api/bpm/approval-tasks").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("待审批"));}
    @Test void processManagerCanAssessBottleneck()throws Exception{String token=login("finance","finance123");mvc.perform(post("/api/bpm/bottleneck-assessment").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"processName\":\"合同审批\",\"averageTaskHours\":30,\"slaHours\":24,\"activeInstances\":20,\"waitingTasks\":15,\"reworkRate\":0.4}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.bottleneckScore").value(85)).andExpect(jsonPath("$.data.level").value("CRITICAL")).andExpect(jsonPath("$.data.predictedDelayHours").value(6.0));}
    @Test void anonymousRequestIsDenied()throws Exception{mvc.perform(get("/api/bpm/process-definitions")).andExpect(status().isForbidden());}
}
